namespace GlobalPayments.Api.Entities {
    public enum ChallengeRequestIndicator {
        NO_PREFERENCE,
        NO_CHALLENGE_REQUESTED,
        CHALLENGE_PREFERRED,
        CHALLENGE_MANDATED,
        NO_CHALLENGE_REQUESTED_TRANSACTION_RISK_ANALYSIS_PERFORMED,
        NO_CHALLENGE_REQUESTED_DATA_SHARE_ONLY,
        NO_CHALLENGE_REQUESTED_SCA_ALREADY_PERFORMED,
        NO_CHALLENGE_REQUESTED_WHITELIST,
        CHALLENGE_REQUESTED_PROMPT_FOR_WHITELIST
    }
}
