using System;
using System.Collections.Generic;
using System.Text;

namespace GlobalPayments.Api.Entities {
    /// <summary>
    /// Represents the action result return by GP API
    /// </summary>
    public class Action {
        /// <summary>
        /// Reprensents a unique identifier generated by Global Payments to identify an action.
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// Indicates the specific action taken.
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// Represents Global Payments time indicating when the object was created in ISO-8601 format.
        /// </summary>
        public string TimeCreated { get; set; }
        /// <summary>
        /// Represents the result of the action executed.
        /// </summary>
        public string ResultCode { get; set; }
        /// <summary>
        /// Represents id of the app that was used to create the token.
        /// </summary>
        public string AppId { get; set; }
        /// <summary>
        /// Represents the name of the app the user gave to the application.
        /// </summary>
        public string AppName { get; set; }
    }
}
