using GlobalPayments.Api.Entities.Enums;
using System;
using System.Collections.Generic;
using System.Text;

namespace GlobalPayments.Api.Entities {

    /// <summary>
    /// Represents the response details for a Pay By Link operation, including link metadata, payment information, and status.
    /// </summary>
    public class PayByLinkResponse {
        /// <summary>
        /// A unique identifier generated by Global Payments to identify the link.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// A meaningful label for the merchant account set by Global Payments.
        /// </summary>
        public string AccountName;

        /// <summary>
        /// The URL that the customer should be redirected to in order to make their payment.
        /// </summary>
        public string Url { get; set; }

        /// <summary>
        /// Indicates where a link is in its lifecycle.
        /// </summary>
        public PayByLinkStatus? Status { get; set; }

        /// <summary>
        /// Describes the type of link that will be created.
        /// </summary>
        public PayByLinkType? Type { get; set; }

        /// <summary>
        /// Indicates whether the link can be used once or multiple times.
        /// </summary>
        public PaymentMethodUsageMode? UsageMode { get; set; }

        /// <summary>
        /// The number of the times that the link can be used or paid.
        /// </summary>
        public int UsageLimit { get; set; }

        /// <summary>
        /// Merchant defined field to reference the transaction.
        /// </summary>
        public string Reference { get; set; }

        /// <summary>
        /// A descriptive name for the link. This will be visible to the customer on the payment page.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// A detailed description of your link that will be visible to the customer on the payment page.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Indicates if you want to capture the customers shipping information on the hosted payment page.
        /// If you enable this field you can also set an optional shipping fee in the shipping_amount.
        /// </summary>
        public bool? IsShippable { get; set; }

        /// <summary>
        /// The number of times a link has been viewed.
        /// </summary>
        public string ViewedCount { get; set; }

        /// <summary>
        /// Indicates the date and time after which the link can no longer be used or paid.
        /// </summary>
        public DateTime? ExpirationDate { get; set; }

        /// <summary>
        /// Images that will be displayed to the customer on the payment page.
        /// </summary>
        public byte[] Images { get; set; }

        /// <summary>
        /// The list of allowed payment methods for this Pay By Link.
        /// </summary>
        public List<PaymentMethodName> AllowedPaymentMethods { get; set; }

        /// <summary>
        /// The email address associated with the application that created the link.
        /// </summary>
        public string AppEmail { get; set; }

        /// <summary>
        /// The unique identifier of the application that created the link.
        /// </summary>
        public string AppId { get; set; }

        /// <summary>
        /// The shipping amount to be charged, if applicable.
        /// </summary>
        public decimal ShippingAmount { get; set; }

        /// <summary>
        /// The channel through which the payment link was created or is intended to be used.
        /// </summary>
        public string Channel { get; set; }

        /// <summary>
        /// The currency code (ISO 4217) for the payment.
        /// </summary>
        public string Currency { get; set; }

        /// <summary>
        /// The amount to be paid by the customer.
        /// </summary>
        public decimal? Amount { get; set; }

        /// <summary>
        /// The country code (ISO 3166-1 alpha-2) associated with the payment or merchant.
        /// </summary>
        public string Country { get; set; }

        /// <summary>
        /// The total order amount, if different from the payment amount.
        /// </summary>
        public decimal? OrderAmount { get; set; }

        /// <summary>
        /// The currency code (ISO 4217) for the order.
        /// </summary>
        public string OrderCurrency { get; set; }

        /// <summary>
        /// The merchant's reference for the order.
        /// </summary>
        public string OrderReference { get; set; }

        /// <summary>
        /// A summary of the action performed, including metadata about the transaction.
        /// </summary>
        public ActionSummary ActionSummary { get; set; }
    }
}
