using System;
using System.Collections.Generic;
using System.Text;

namespace GlobalPayments.Api.Network.Entities {
    public class RecordDataEntry {
        public string MessageVersion { get; set; }
        public string TransactionDate { get; set; }
        public string TransactionTime { get; set; }
        public string CompanyName { get; set; }
        public string HeartlandCompanyId { get; set; }
        public string MerchantName { get; set; }
        public string MerchantId { get; set; }
        public string MerchantStreet { get; set; }
        public string MerchantCity { get; set; }
        public string MerchantState { get; set; }
        public string MerchantZIP { get; set; }
        public string MerchantPhoneNumber { get; set; }
        public string SiteBrand { get; set; }
        public string MerchantType { get; set; }
        public string POSApplicationType { get; set; }
        public string OperationMethod { get; set; }
        public string POSVendor { get; set; }
        public string POSModel { get; set; }
        public string POSTerminalType { get; set; }
        public string POSSoftwareVersion { get; set; }
        public string POSSpecification { get; set; }
        public string POSSpecificationVersion { get; set; }
        public string PaymentEngine { get; set; }
        public string PaymentVertical { get; set; }
        public string HardwareVersion { get; set; }
        public string SoftwareVersion { get; set; }
        public string FirmwareLevel { get; set; }
        public string MiddlewareVendor { get; set; }
        public string MiddlewareModel { get; set; }
        public string MiddlewareType { get; set; }
        public string MiddlewareSoftwareVersion { get; set; }
        public string ReceiptPrinterType { get; set; }
        public string ReceiptPrinterModel { get; set; }
        public string JournalPrinterType { get; set; }
        public string JournalPrinterModel { get; set; }
        public string MultiLaneDeviceType { get; set; }
        public string MultiLaneDeviceVendor { get; set; }
        public string MultiLaneDeviceModel { get; set; }
        public string InsideKeyManagementScheme { get; set; }
        public string InsidePINEncryption { get; set; }
        public string OutsidePEDType { get; set; }
        public string OutsidePEDVendor { get; set; }
        public string OutsidePEDModel { get; set; }
        public string OutsideKeyManagementScheme { get; set; }
        public string OutsidePINEncryption { get; set; }
        public string CheckReaderVendor { get; set; }
        public string CheckReaderModel { get; set; }
        public string InsideContactlessReaderType { get; set; }
        public string InsideContactlessReaderVendor { get; set; }
        public string InsideContactlessReaderModel { get; set; }
        public string OutsideContactlessReaderType { get; set; }
        public string OutsideContactlessReaderVendor { get; set; }
        public string OutsideContactlessReaderModel { get; set; }
        public string CommunicationMedia { get; set; }
        public string CommunicationProtocol { get; set; }
        public string BroadbandUse { get; set; }
        public string DataWireAccess { get; set; }
        public string MicroNodeModelNumber { get; set; }
        public string MicroNodeSoftwareVersion { get; set; }
        public string RouterType { get; set; }
        public string RouterVendor { get; set; }
        public string RouterProductModel { get; set; }
        public string ModemPhoneNumber { get; set; }
        public string PrimaryDialNumberOrIPAddress { get; set; }
        public string SecondaryDialNumberOrIPAddress { get; set; }
        public string DispenserInterfaceVendor { get; set; }
        public string DispenserInterfaceModel { get; set; }
        public string DispenserInterfaceSoftwareVersion { get; set; }
        public string DispenserVendor { get; set; }
        public string DispenserModel { get; set; }
        public string DispenserSoftwareVersion { get; set; }
        public string DispenserQuantity { get; set; }
        public string NumberOfScannersOrPeripherals { get; set; }
        public string Scanner1Vendor { get; set; }
        public string Scanner1Model { get; set; }
        public string Scanner1SoftwareVersion { get; set; }
        public string Peripheral2Vendor { get; set; }
        public string Peripheral2Model { get; set; }
        public string Peripheral2SoftwareVersion { get; set; }
        public string Peripheral3Vendor { get; set; }
        public string Peripheral3Model { get; set; }
        public string Peripheral3SoftwareVersion { get; set; }
        public string Peripheral4Vendor { get; set; }
        public string Peripheral4Model { get; set; }
        public string Peripheral4SoftwareVersion { get; set; }
        public string Peripheral5Vendor { get; set; }
        public string Peripheral5Model { get; set; }
        public string Peripheral5SoftwareVersion { get; set; }
    }
}
